workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - quanganhng14@gmail.com
          - phamhuudatk58@gmail.com